services:
  pg:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=easyproject-saas
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: